name: Create Releases

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git Tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Get Current Version
      id: get_version
      run: |
        TAG=$(git describe --tags --abbrev=0)
        echo "CURRENT_VERSION=$TAG" >> $GITHUB_ENV
        echo "CURRENT_VERSION=$TAG" >> $GITHUB_OUTPUT

    - name: Increment Version
      id: increment_version
      run: |
        IFS='.' read -ra VER <<< "${{ steps.get_version.outputs.CURRENT_VERSION }}"
        if [ "${{ github.event_name }}" == "push" ]; then
          ((VER[2]++))
        else
          ((VER[1]++))
          VER[2]=0
        fi
        NEW_TAG="v0.${VER[1]}.${VER[2]}"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_OUTPUT

    # Add steps for your build/testing here

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.increment_version.outputs.NEW_TAG }}
        release_name: Release ${{ steps.increment_version.outputs.NEW_TAG }}
        draft: false
        prerelease: false
